#!/usr/bin/env python
import optparse
import sys
import math

# READ the data (translations.tsv)
optparser = optparse.OptionParser()
optparser.add_option("-r", "--readTranslationFiles", dest="input", default="data-test/test_translations.tsv", help="Read Translation Files.")
optparser.add_option("-d", "--defaultData", dest="data", default=None, help="Write data")
(opts, _) = optparser.parse_args()

# Open the data file, and start parsing
file = open(opts.input)
txt = file.readlines()
header = txt[0]

# Due to the format of the data, preprocessing is done to generate:
# Candidate Dictionary (each source sentence has 4 candidate sentences) 
# Source Dictionary (original Urdu sentence)
# Worker Dictionary (individual non-professional's id assigned from Amazon. Possibly used in ML extensions)
candidateDict = {}
sourceDict = {}
workerDict = {}

for i in xrange(1, len(txt)):
    sentenceList = txt[i].split("\t")
    sourceDict[i] = sentenceList[1] #Urdu
    candidateDict[i] = sentenceList[2:6] #Non-professionally translated sentences
    workerDict[i] = sentenceList[6:10] #Individual worker id

#DEFAULT: Choose first candidate sentence among 4 possible sentences


if opts.data is None:
	for i in xrange(1, len(candidateDict) + 1):
		sys.stdout.write(candidateDict[i][0] + '\n')
else:
	for i in xrange(1, len(candidateDict) + 1):
		sys.stdout.write(candidateDict[i][0] + '\n')

